feature_lesson6
dymont78/HerokuApp pull request #1
Opened 2021-05-06 08:32 UTC by dymont78

2021-05-06 12:45 UTC, vchesnakoutest requested changes
please make fixes

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/HerokuAppTest.java
> +        //driver.quit();
старайся не оставлять закоменченый код (проверь также остальные места)

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/HerokuAppTest.java
> +        System.out.println("Количество оставшихся элементов: " + elements.size());
нету Assert'a

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/HerokuAppTest.java
> +
пустые строки лучше убирать

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/herokuAppTestCheckBox.java
> +    public void herokuAppTestCheckBox(){
названия тестовых методов должны заканчиваться на Test (проверь остальные тоже)

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/herokuAppTestCheckBox.java
> +        boolean isCheckBoxActuals = firstCheckBox.isSelected();
isCheckBoxSelected

2021-05-06 12:45 UTC, vchesnakoutest commented on src/test/java/tests/herokuAppTestCheckBox.java
> +        if (!isCheckBoxActuals) System.out.println("Checkbox2 unchecked");
нету Assert' ов

2021-05-09 11:20 UTC, merged

2021-05-09 11:22 UTC, dymont78 commented
Update herokuAppTest.java, Update herokuAppTestCheckBox.java